project_id = "saxwbdwmuzkmxztagfot"

[functions.calculate-delivery-fee]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = false

[functions.create-driver-auth]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
