project_id = "saxwbdwmuzkmxztagfot"

[functions.calculate-delivery-fee]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = false

[functions.create-driver-auth]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false

[functions.send-sms-notification]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.admin-user-management]
verify_jwt = false

[functions.auth-by-username]
verify_jwt = false

[functions.save-abandoned-checkout]
verify_jwt = false

[functions.recover-abandoned-checkout]
verify_jwt = false

[functions.send-cart-reminder]
verify_jwt = false
